### PR TITLE
Fix .gitpod.yml syntax

### PR DESCRIPTION
**Pull request by jankeromnes**
Hi @Pierstoval,

(I just saw https://twitter.com/Pierstoval/status/1224268909601267713 and was excited to discover you tried Gitpod 🙂 I hope you like it! I'm one of their developers)

I also noticed that your `.gitpod.yml` was close to perfect, but just had a small syntax error.

I also took the liberty to move the `symfony` install to a Dockerfile, so that you don't have to wait for it every time you start a workspace.

Caveat: This doesn't fully work just yet, because I noticed our PHP version is out-dated (7.2, while you require 7.4). I'll just upgrade Gitpod's default PHP version now. 😄

### CODE REVIEW

**Comment by Pierstoval** [comment]
I was actually about to work on it locally 😄 

Since PHP 7.4 was unavailable I will also publish soon a Dockerfile with PHP 7.4 and the Symfony CLI, this will help set up the project for Heroku (since they don't have php 7.4 either 🤣  )

I can't wait for 7.4 to be available on Gitpod so I can try to set up the project with it!

Thanks a lot for your contribution 🚀

**Comment by jankeromnes** [comment]
@Pierstoval Thanks for the quick review! 🚀 

FYI this is [how we currently install PHP](https://github.com/gitpod-io/workspace-images/blob/c90b4a5ce44b8956cfd278f67422c739e07ff80e/full/Dockerfile#L65-L88) on Gitpod. Since we're based on Ubuntu Disco 19.04, I guess our only option to upgrade to PHP 7.4 is to use `ppa:ondrej/php` as suggested in [this article](https://www.colinodell.com/blog/201911/how-to-install-php-74) (and replace all the `php-*` packages with `php7.4-*` 😕).

I also tried `brew install php` (Homebrew works on Gitpod btw 😄), but that takes a lot of time pulling in many dependencies, and only installs PHP 7.3 anyway.

**Comment by Pierstoval** [comment]
Have you considerd switching to https://github.com/phpenv/phpenv and allow users to add more PHP versions?
This would allow projects using older versions too 😄

**Comment by jankeromnes** [comment]
> Have you considerd switching to https://github.com/phpenv/phpenv and allow users to add more PHP versions?
> This would allow projects using older versions too 😄

Sounds useful! Thanks a lot for the tip. 💯 

In your experience, do PHP developers/projects often require a specific PHP version (i.e. not latest stable)?

Also, is `phpenv` a well-known tool, i.e. PHP developers would be able to find it in Gitpod without reading somewhere that it's available first?

Thanks for the insights about official PHP docker images (which should in theory work with Gitpod too) and `ppa:ondrej/php` for the rest. (FYI for `clang` we also use a PPA that ships suffixed packages like `clang-10`, `clangd-10`, `lld-10`, etc. So we could potentially do it for PHP 7.4 as well.)

**Comment by Pierstoval** [comment]
Most applications need _at least_ a minimum PHP version.

It's important to be as close as possible to production, and applications are less compatible with "newer versions" than frameworks are.

The best solution is to make sure _any_ PHP version could be supported, of course, but of course having all the recent versions is nice too (php 7.1 to 7.4 included).

Also, PHP 8 will probably come in 2021 so it's important IMO to prepare the support for it, and phpenv seems like a nice solution. The necessary setup is quite different (you don't use native packages, since PHP is rebuilt from source), but it allows you as a maintainer to install phpenv in a main docker image, and provide one new docker image for each php version, or let the user install the version by themselves.

But the https://deb.sury.org/ repo is okay since it already provides many PHP versions (as of today, it has 5.6 to 7.4) that anyone could install even if you choose 7.4 as default 😄

**Comment by jankeromnes** [comment]
Many thanks for these precious insights! 🙏 

I'll try to decide on one option soon, and then upgrade Gitpod's default PHP version to 7.4. Also I'll try to ping you here when it ships. 🙂

**Comment by Pierstoval** [comment]
Awesome! Do you need some help with the Docker image? :)

**Comment by Lctrs** [comment]
Isn't it possible to install PHP 7.4 via `brew` ?

**Comment by Pierstoval** [comment]
You can have php 7.4 on your machine.

Brew is only for Mac.

I'm not sure Gitpod is using Mac.

**Comment by Lctrs** [comment]
There is a version of Brew for Linux and it is definitively installed on Gitpod. So you can have PHP 7.4 through it on Gitpod. Just tested and after manipulating the PATH, it works.

**Comment by jankeromnes** [comment]
> Awesome! Do you need some help with the Docker image? :)

Hey, that's very nice of you to offer, thank you @Pierstoval. 🙏 If you're still interested, could you please make a PR to update these lines to PHP 7.4?

https://github.com/gitpod-io/workspace-images/blob/5a302cc8c16bfa5ce9151b6f88a37328d23bd7d5/full/Dockerfile#L72-L100

(I think it's cool to upgrade Gitpod's default workspace image to PHP to 7.4 directly, instead of setting up an intermediate version manager like `phpenv`, because that would potentially make the setup more complicated and the image size larger.)

> Isn't it possible to install PHP 7.4 via `brew` ?
> 
> `$ brew install php@7.4`

@Lctrs Excellent point!

@Pierstoval HomeBrew works on Linux too now: https://docs.brew.sh/Homebrew-on-Linux -- And iIt's installed by default in Gitpod workspaces, because we find it pretty convenient: https://www.gitpod.io/blog/brew/

In general, I would say that `brew install php@7.4` is a good solution for anyone customizing their project's Gitpod workspace image, but maybe for Gitpod's default images, we can afford using the more complicated `apt-add-repository && apt-get update && apt-get install && rm sources`, thus making our Dockerfiles look more complicated & verbose, but producing smaller images as a trade-off.

**Comment by jankeromnes** [comment]
Quick updates on PHP in Gitpod:

- I'm trying to upgrade Gitpod to PHP 7.4 using `ppa:ondrej/php` in https://github.com/gitpod-io/workspace-images/pull/199. Unfortunately, this doesn't work, because the PPA removed support for Ubuntu 19.04, which Gitpod still uses even though it was end-of-life'd on 22 January 2020.

- I'm also trying to upgrade Gitpod to Ubuntu 20.04 LTS (officially released in a few weeks I think, but Docker images already seem to be available) in https://github.com/gitpod-io/workspace-images/pull/197. This would make the other PR obsolete, because I think Ubuntu 20.04 already comes with PHP 7.4 by default. However, it currently doesn't work because the package `php-gettext` is not yet or no longer available.

**Comment by Pierstoval** [comment]
> * because I think Ubuntu 20.04 already comes with PHP 7.4 by default

I confirm 😄  https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#PHP_7.4

It's going to be good if we can use Ubuntu 20.04 in Gitpod, so I will definitely don't mind waiting till the next month for it, if it can ease maintenance for you 😄

**Comment by jankeromnes** [comment]
Ubuntu 20.04 upgrade is now live! 🎉 😄 (see edit)

**Pull request merged**
