### PR TITLE
Start working on a PHP docker setup

### PR DESCRIPTION
**Pull request by Pierstoval**
It's not working for now, and I'm not even sure that I want this, but this could definitely help people that don't want a PHP 7.4 + Symfony CLI setup on their machine.

Maybe we could do the same with Node.js for Webpack Encore too, but... Node.js 😄

### CODE REVIEW

**Comment by gabiudrescu** [comment]
why don't you build on top of Sylius Docker? https://github.com/Sylius/Sylius-Standard/blob/master/Dockerfile

**Comment by Pierstoval** [comment]
Well, there are several Dockerfiles for PHP applications, I wish to create a straightforward for each release of Compotes that contain the strict minimum to execute the app in a dev and prod environment (meaning 2 dockerfiles then).

Plus, Sylius' one is based on alpine, and I don't want that 😄 Using plain Debian + native php binaries is easier IMO

**Comment by gabiudrescu** [comment]
yeah, but alpine images are smaller and should allow better portability / faster compiling time

**Comment by Pierstoval** [comment]
In such case, I'm trading "fast&small" for "closer to prod" because I don't think people will install this on docker clusters or such, hence the fact that I prefer a plain debian build.

But if later the need for alpine comes, maybe we'll provide different dockerfiles :)

**Comment by Pierstoval** [comment]
I made a basic setup, it currently works like a charm, all I need to do is determine what kind of docker image I want 😄

**Comment by Pierstoval** [comment]
Docker images are ready, but it seems that the Github Action cannot build it because of volume issues. 

It seems that we'll have to wait until Github upgrades Docker in its machines.

**Comment by Pierstoval** [comment]
It works, let's merge it

**Pull request merged**
